config/routes.rb
Rails.application.routes.draw do

  get "/", :controller => "encounters", :action => "new"

  get "/encounters/new", :controller => "encounters", :action => "new"
  post "/create_encounter", :controller => "encounters", :action => "create"

  get "/encounters", :controller => "encounters", :action => "index"
  get "/encounters/:id", :controller => "encounters", :action => "show"

  get "/encounters/:id/edit", :controller => "encounters", :action => "edit"
  post "/update_encounter/:id", :controller => "encounters", :action => "update"

  get "/delete_encounter/:id", :controller => "encounters", :action => "destroy"

  devise_for :users

end

app/models/encounter.rb
class Encounter < ActiveRecord::Base

  require 'csv'

  def self.import(file)
      CSV.foreach(file.path, headers: true) do |row|
      Encounter.create! row.to_hash
    end
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController



  def index
    @encounters = Encounter.all
  end

  def show
    @encounter = Encounter.find(params[:id])
  end

  def new

  end

  def create

    Encounter.import(params[:file])

    redirect_to "/", notice: "Encounter Data Imported"

  end



  def edit
    @encounter = Encounter.find(params[:id])
  end

  def update
    @encounter = Encounter.find(params[:id])

    @encounter.obs_exp_readmit_difference = params[:obs_exp_readmit_difference]
    @encounter.readmit_exp = params[:readmit_exp]
    @encounter.obs_exp_cost_difference = params[:obs_exp_cost_difference]
    @encounter.expected_direct_cost = params[:expected_direct_cost]
    @encounter.risk_adjusted_cost = params[:risk_adjusted_cost]
    @encounter.average_bundle_cost = params[:average_bundle_cost]
    @encounter.risk_score = params[:risk_score]
    @encounter.combined_bundle_icd9 = params[:combined_bundle_icd9]
    @encounter.bundle_name = params[:bundle_name]
    @encounter.readmit_days_from_discharge = params[:readmit_days_from_discharge]
    @encounter.readmission = params[:readmission]
    @encounter.had_readmission = params[:had_readmission]
    @encounter.total_ip_visits = params[:total_ip_visits]
    @encounter.uniqueid = params[:uniqueid]
    @encounter.contribution_margin = params[:contribution_margin]
    @encounter.cases = params[:cases]
    @encounter.direct_costs = params[:direct_costs]
    @encounter.fixed_costs = params[:fixed_costs]
    @encounter.actual_payment = params[:actual_payment]
    @encounter.total_adjustment = params[:total_adjustment]
    @encounter.total_charges = params[:total_charges]
    @encounter.payor_group = params[:payor_group]
    @encounter.payor_type = params[:payor_type]
    @encounter.discharge_disposition = params[:discharge_disposition]
    @encounter.discharge_date = params[:discharge_date]
    @encounter.admit_date = params[:admit_date]
    @encounter.facility_name = params[:facility_name]
    @encounter.attending_physician_description = params[:attending_physician_description]
    @encounter.attending_physician_id = params[:attending_physician_id]
    @encounter.admitting_physician_description = params[:admitting_physician_description]
    @encounter.admitting_physician_id = params[:admitting_physician_id]
    @encounter.primary_icd9_poa = params[:primary_icd9_poa]
    @encounter.primary_icd9_description = params[:primary_icd9_description]
    @encounter.primary_icd9 = params[:primary_icd9]
    @encounter.msdrg_description = params[:msdrg_description]
    @encounter.msdrg = params[:msdrg]
    @encounter.icd9_procedure = params[:icd9_procedure]
    @encounter.admit_source = params[:admit_source]
    @encounter.length_of_stay = params[:length_of_stay]
    @encounter.zip_code = params[:zip_code]
    @encounter.gender = params[:gender]
    @encounter.age = params[:age]
    @encounter.birth_date = params[:birth_date]
    @encounter.standard_id = params[:standard_id]
    @encounter.patient_account = params[:patient_account]

    if @encounter.save
      redirect_to "/encounters", :notice => "Encounter updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @encounter = Encounter.find(params[:id])

    @encounter.destroy

    redirect_to "/encounters", :notice => "Encounter deleted."
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/encounters/index.html.erb
<div class="page-header">
  <h1>
    Encounters
    <a href="/encounters/new" class="btn btn-lg btn-success">New Encounter</a>
  </h1>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-hover">
      <tr>
        <th>Obs exp readmit difference</th>
        <th>Readmit exp</th>
        <th>Obs exp cost difference</th>
        <th>Expected direct cost</th>
        <th>Risk adjusted cost</th>
        <th>Average bundle cost</th>
        <th>Risk score</th>
        <th>Combined bundle icd9</th>
        <th>Bundle name</th>
        <th>Readmit days from discharge</th>
        <th>Readmission</th>
        <th>Had readmission</th>
        <th>Total ip visits</th>
        <th>Uniqueid</th>
        <th>Contribution margin</th>
        <th>Cases</th>
        <th>Direct costs</th>
        <th>Fixed costs</th>
        <th>Actual payment</th>
        <th>Total adjustment</th>
        <th>Total charges</th>
        <th>Payor group</th>
        <th>Payor type</th>
        <th>Discharge disposition</th>
        <th>Discharge date</th>
        <th>Admit date</th>
        <th>Facility name</th>
        <th>Attending physician description</th>
        <th>Attending physician</th>
        <th>Admitting physician description</th>
        <th>Admitting physician</th>
        <th>Primary icd9 poa</th>
        <th>Primary icd9 description</th>
        <th>Primary icd9</th>
        <th>Msdrg description</th>
        <th>Msdrg</th>
        <th>Icd9 procedure</th>
        <th>Admit source</th>
        <th>Length of stay</th>
        <th>Zip code</th>
        <th>Gender</th>
        <th>Age</th>
        <th>Birth date</th>
        <th>Standard</th>
        <th>Patient account</th>
        <th>Actions</th>
      </tr>

      <% @encounters.each do |encounter| %>
      <tr>
        <td><%= encounter.obs_exp_readmit_difference %></td>
        <td><%= encounter.readmit_exp %></td>
        <td><%= encounter.obs_exp_cost_difference %></td>
        <td><%= encounter.expected_direct_cost %></td>
        <td><%= encounter.risk_adjusted_cost %></td>
        <td><%= encounter.average_bundle_cost %></td>
        <td><%= encounter.risk_score %></td>
        <td><%= encounter.combined_bundle_icd9 %></td>
        <td><%= encounter.bundle_name %></td>
        <td><%= encounter.readmit_days_from_discharge %></td>
        <td><%= encounter.readmission %></td>
        <td><%= encounter.had_readmission %></td>
        <td><%= encounter.total_ip_visits %></td>
        <td><%= encounter.uniqueid %></td>
        <td><%= encounter.contribution_margin %></td>
        <td><%= encounter.cases %></td>
        <td><%= encounter.direct_costs %></td>
        <td><%= encounter.fixed_costs %></td>
        <td><%= encounter.actual_payment %></td>
        <td><%= encounter.total_adjustment %></td>
        <td><%= encounter.total_charges %></td>
        <td><%= encounter.payor_group %></td>
        <td><%= encounter.payor_type %></td>
        <td><%= encounter.discharge_disposition %></td>
        <td><%= encounter.discharge_date %></td>
        <td><%= encounter.admit_date %></td>
        <td><%= encounter.facility_name %></td>
        <td><%= encounter.attending_physician_description %></td>
        <td><%= encounter.attending_physician_id %></td>
        <td><%= encounter.admitting_physician_description %></td>
        <td><%= encounter.admitting_physician_id %></td>
        <td><%= encounter.primary_icd9_poa %></td>
        <td><%= encounter.primary_icd9_description %></td>
        <td><%= encounter.primary_icd9 %></td>
        <td><%= encounter.msdrg_description %></td>
        <td><%= encounter.msdrg %></td>
        <td><%= encounter.icd9_procedure %></td>
        <td><%= encounter.admit_source %></td>
        <td><%= encounter.length_of_stay %></td>
        <td><%= encounter.zip_code %></td>
        <td><%= encounter.gender %></td>
        <td><%= encounter.age %></td>
        <td><%= encounter.birth_date %></td>
        <td><%= encounter.standard_id %></td>
        <td><%= encounter.patient_account %></td>
        <td>
          <a href="/encounters/<%= encounter.id %>" class="btn btn-primary">Show</a>
          <a href="/encounters/<%= encounter.id %>/edit" class="btn btn-warning">Edit</a>
          <a href="/delete_encounter/<%= encounter.id %>" class="btn btn-danger" rel="nofollow">Delete</a>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/encounters/new.html.erb
<div class="page-header">
  <h3>Physician Dashboard</h3>

</div>

<div class="row">
  <div class="col-md-12">

<div class="panel panel-info" >
  <div class="panel-heading">
    <div class="panel-title">Most Popular</div>
  </div>

<div style="padding-top:20px" class="panel-body" >
  <div class="col-md-6 col-md-offset-0">
        <div class="chart-wrapper">
          <div class="chart-title">
            Physicians
          </div>
          <div class="chart-stage">

          <%=  bar_chart Encounter.where(bundle_name: "Major Joint Replacement").group(:attending_physician_description).order('count_all DESC').limit(15).count %>


         </div>
        </div>
      </div>

  <div class="col-md-6 col-md-offset-0">
        <div class="chart-wrapper">
          <div class="chart-title">
            Facilities
          </div>
          <div class="chart-stage">

          <%=  bar_chart Encounter.where(bundle_name: "Major Joint Replacement").group(:facility_name).order('count_all DESC').limit(15).count %>


          </div>
        </div>
      </div>
</div>
</div>
<div class="panel panel-success" >
  <div class="panel-heading">
    <div class="panel-title">Your Performance</div>
  </div>

<div style="padding-top:20px" class="panel-body" >
  <div class="col-md-6 col-md-offset-0">
        <div class="chart-wrapper">
          <div class="chart-title">
            % Readmissions by Month
          </div>
          <div class="chart-stage">

          <%=  line_chart Encounter.where(attending_physician_description: "EMERSON ROGER").group_by{ |t| t.discharge_date.beginning_of_month }.count %>


         </div>
        </div>
      </div>

  <div class="col-md-6 col-md-offset-0">
        <div class="chart-wrapper">
          <div class="chart-title">
            Facilities
          </div>
          <div class="chart-stage">

          <%=  bar_chart Encounter.where(bundle_name: "Major Joint Replacement").group(:facility_name).order('count_all DESC').limit(15).count %>


          </div>
        </div>
      </div>


</div>
</div>


  </div>
</div>

app/views/encounters/show.html.erb
<div class="page-header">
  <h3>Encounter #<%= @encounter.id %></h3>
</div>

<div class="row">
  <div class="col-md-12">
    <dl class="dl-horizontal">
      <dt>Obs exp readmit difference</dt>
      <dd><%= @encounter.obs_exp_readmit_difference %></dd>

      <dt>Readmit exp</dt>
      <dd><%= @encounter.readmit_exp %></dd>

      <dt>Obs exp cost difference</dt>
      <dd><%= @encounter.obs_exp_cost_difference %></dd>

      <dt>Expected direct cost</dt>
      <dd><%= @encounter.expected_direct_cost %></dd>

      <dt>Risk adjusted cost</dt>
      <dd><%= @encounter.risk_adjusted_cost %></dd>

      <dt>Average bundle cost</dt>
      <dd><%= @encounter.average_bundle_cost %></dd>

      <dt>Risk score</dt>
      <dd><%= @encounter.risk_score %></dd>

      <dt>Combined bundle icd9</dt>
      <dd><%= @encounter.combined_bundle_icd9 %></dd>

      <dt>Bundle name</dt>
      <dd><%= @encounter.bundle_name %></dd>

      <dt>Readmit days from discharge</dt>
      <dd><%= @encounter.readmit_days_from_discharge %></dd>

      <dt>Readmission</dt>
      <dd><%= @encounter.readmission %></dd>

      <dt>Had readmission</dt>
      <dd><%= @encounter.had_readmission %></dd>

      <dt>Total ip visits</dt>
      <dd><%= @encounter.total_ip_visits %></dd>

      <dt>Uniqueid</dt>
      <dd><%= @encounter.uniqueid %></dd>

      <dt>Contribution margin</dt>
      <dd><%= @encounter.contribution_margin %></dd>

      <dt>Cases</dt>
      <dd><%= @encounter.cases %></dd>

      <dt>Direct costs</dt>
      <dd><%= @encounter.direct_costs %></dd>

      <dt>Fixed costs</dt>
      <dd><%= @encounter.fixed_costs %></dd>

      <dt>Actual payment</dt>
      <dd><%= @encounter.actual_payment %></dd>

      <dt>Total adjustment</dt>
      <dd><%= @encounter.total_adjustment %></dd>

      <dt>Total charges</dt>
      <dd><%= @encounter.total_charges %></dd>

      <dt>Payor group</dt>
      <dd><%= @encounter.payor_group %></dd>

      <dt>Payor type</dt>
      <dd><%= @encounter.payor_type %></dd>

      <dt>Discharge disposition</dt>
      <dd><%= @encounter.discharge_disposition %></dd>

      <dt>Discharge date</dt>
      <dd><%= @encounter.discharge_date %></dd>

      <dt>Admit date</dt>
      <dd><%= @encounter.admit_date %></dd>

      <dt>Facility name</dt>
      <dd><%= @encounter.facility_name %></dd>

      <dt>Attending physician description</dt>
      <dd><%= @encounter.attending_physician_description %></dd>

      <dt>Attending physician</dt>
      <dd><%= @encounter.attending_physician_id %></dd>

      <dt>Admitting physician description</dt>
      <dd><%= @encounter.admitting_physician_description %></dd>

      <dt>Admitting physician</dt>
      <dd><%= @encounter.admitting_physician_id %></dd>

      <dt>Primary icd9 poa</dt>
      <dd><%= @encounter.primary_icd9_poa %></dd>

      <dt>Primary icd9 description</dt>
      <dd><%= @encounter.primary_icd9_description %></dd>

      <dt>Primary icd9</dt>
      <dd><%= @encounter.primary_icd9 %></dd>

      <dt>Msdrg description</dt>
      <dd><%= @encounter.msdrg_description %></dd>

      <dt>Msdrg</dt>
      <dd><%= @encounter.msdrg %></dd>

      <dt>Icd9 procedure</dt>
      <dd><%= @encounter.icd9_procedure %></dd>

      <dt>Admit source</dt>
      <dd><%= @encounter.admit_source %></dd>

      <dt>Length of stay</dt>
      <dd><%= @encounter.length_of_stay %></dd>

      <dt>Zip code</dt>
      <dd><%= @encounter.zip_code %></dd>

      <dt>Gender</dt>
      <dd><%= @encounter.gender %></dd>

      <dt>Age</dt>
      <dd><%= @encounter.age %></dd>

      <dt>Birth date</dt>
      <dd><%= @encounter.birth_date %></dd>

      <dt>Standard</dt>
      <dd><%= @encounter.standard_id %></dd>

      <dt>Patient account</dt>
      <dd><%= @encounter.patient_account %></dd>

    </dl>

    <div class="btn-group btn-group-justified">
      <a href="/encounters" class="btn btn-primary">
        Back
      </a>
      <a href="/encounters/<%= @encounter.id %>/edit" class="btn btn-warning">
        Edit
      </a>
      <a href="/delete_encounter/<%= @encounter.id %>" class="btn btn-danger" rel="nofollow">
        Delete
      </a>
    </div>
  </div>
</div>

app/views/encounters/upload.html.erb
<div class="page-header">
  <h3>Upload Encounter Data</h3>

</div>

<div class="row">
  <div class="col-md-12">

    <br>

    <%= form_tag create_encounter_path, multipart: true do %>

    <%= file_field_tag :file %>

    <br>
    <br>

    <%= submit_tag "Upload Data", :class => 'btn btn-success' %>

    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>BCG Health Analytics</title>

  <link rel="stylesheet" href="assets/bootstrap.css">
  <link rel="stylesheet" href="assets/keen-dashboards.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <!--jQuery -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>

  <!-- Bootstrap JS -->
  <script src="/assets/bootstrap.js"></script>
  <script src="/assets/highcharts.js" type="text/javascript"></script>
  <script src="/assets/chartkick.js" type="text/javascript"></script>


  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 60px;
    }
  </style>


  <%= csrf_meta_tags %>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand">BCG Health Analytics</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/encounters">Dashboard</a></li>
          <li><a href="/rails/info">Admin Tools</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="/users/sign_out" data-method="delete" rel="nofollow">Sign Out</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>